import tkinter as tk

# PATCH: replace rounded_rect in interface.py with this implementation.
# The previous version passed arc coordinates as positional arguments; Tkinter
# expects the bounding box as one 4-item sequence, followed by start/extent.

def _fixed_rounded_rect(self, x1, y1, x2, y2, radius=28, fill="", outline="", width=1, tags=None):
    radius = max(0, min(radius, abs(x2 - x1) / 2, abs(y2 - y1) / 2))
    if radius == 0:
        self.canvas.create_rectangle(x1, y1, x2, y2, fill=fill, outline=outline, width=width, tags=tags)
        return

    # Main fill
    self.canvas.create_rectangle(x1 + radius, y1, x2 - radius, y2, fill=fill, outline="", tags=tags)
    self.canvas.create_rectangle(x1, y1 + radius, x2, y2 - radius, fill=fill, outline="", tags=tags)

    # Four filled corners
    self.canvas.create_arc((x1, y1, x1 + 2 * radius, y1 + 2 * radius), start=90, extent=90, fill=fill, outline=fill, tags=tags)
    self.canvas.create_arc((x2 - 2 * radius, y1, x2, y1 + 2 * radius), start=0, extent=90, fill=fill, outline=fill, tags=tags)
    self.canvas.create_arc((x1, y2 - 2 * radius, x1 + 2 * radius, y2), start=180, extent=90, fill=fill, outline=fill, tags=tags)
    self.canvas.create_arc((x2 - 2 * radius, y2 - 2 * radius, x2, y2), start=270, extent=90, fill=fill, outline=fill, tags=tags)

    if outline:
        # Border arcs
        self.canvas.create_arc((x1, y1, x1 + 2 * radius, y1 + 2 * radius), start=90, extent=90, style="arc", outline=outline, width=width, tags=tags)
        self.canvas.create_arc((x2 - 2 * radius, y1, x2, y1 + 2 * radius), start=0, extent=90, style="arc", outline=outline, width=width, tags=tags)
        self.canvas.create_arc((x1, y2 - 2 * radius, x1 + 2 * radius, y2), start=180, extent=90, style="arc", outline=outline, width=width, tags=tags)
        self.canvas.create_arc((x2 - 2 * radius, y2 - 2 * radius, x2, y2), start=270, extent=90, style="arc", outline=outline, width=width, tags=tags)
        self.canvas.create_line(x1 + radius, y1, x2 - radius, y1, fill=outline, width=width, tags=tags)
        self.canvas.create_line(x1 + radius, y2, x2 - radius, y2, fill=outline, width=width, tags=tags)
        self.canvas.create_line(x1, y1 + radius, x1, y2 - radius, fill=outline, width=width, tags=tags)
        self.canvas.create_line(x2, y1 + radius, x2, y2 - radius, fill=outline, width=width, tags=tags)

# NOTE: This is a temporary replacement file generated by the assistant.
# The existing interface.py class should bind this function to the class as:
# XenovaInterface.rounded_rect = _fixed_rounded_rect
